//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bogOrder
    {
        public string orderId { get; set; }
        public string paymentHash { get; set; }
        public byte[] ipayPaymentId { get; set; }
        public int bogStatusId { get; set; }
        public string statusDescription { get; set; }
        public long shopOrderId { get; set; }
        public int bogPaymentMethodId { get; set; }
        public int bogCardTypeId { get; set; }
        public string transactionId { get; set; }
        public string pan { get; set; }
    
        public virtual BogCardType BogCardType { get; set; }
        public virtual ServiceOrder ServiceOrder { get; set; }
        public virtual BogPaymentMethod BogPaymentMethod { get; set; }
        public virtual BogStatus BogStatus { get; set; }
    }
}
