//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public int ConnectedUserId { get; set; }
        public int SenderId { get; set; }
        public string Message1 { get; set; }
        public System.DateTime SendingDate { get; set; }
        public bool Seen { get; set; }
    
        public virtual ConnectedUser ConnectedUser { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
