//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Media = new HashSet<Medium>();
            this.PropertyContents = new HashSet<PropertyContent>();
            this.PropertyFeatures = new HashSet<PropertyFeature>();
            this.PropertyServices = new HashSet<PropertyService>();
            this.PropertyViews = new HashSet<PropertyView>();
            this.Reviews = new HashSet<Review>();
            this.Favorites = new HashSet<Favorite>();
            this.UserActivities = new HashSet<UserActivity>();
        }
    
        public int Id { get; set; }
        public decimal Price { get; set; }
        public decimal PropertySize { get; set; }
        public Nullable<int> PropertyTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string CadastralCode { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> Floors { get; set; }
        public int Rooms { get; set; }
        public int Bedrooms { get; set; }
        public decimal CeilingSize { get; set; }
        public string PhoneNumber { get; set; }
        public decimal WholePrice { get; set; }
        public System.DateTime DatePublished { get; set; }
        public int UserDetailsId { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Bathrooms { get; set; }
        public Nullable<int> Garages { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> CurrentStatusId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medium> Media { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual State State { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyContent> PropertyContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyFeature> PropertyFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyService> PropertyServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyView> PropertyViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual CurrentStatu CurrentStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserActivity> UserActivities { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
