//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyService
    {
        public int Id { get; set; }
        public int ServicesId { get; set; }
        public int PropertyId { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public bool Active { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Service Service { get; set; }
    }
}
