//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyContent
    {
        public int Id { get; set; }
        public int propertyId { get; set; }
        public int contentId { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Property Property { get; set; }
    }
}
