//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int UserDetailsId { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public string Comment { get; set; }
        public int PropertyId { get; set; }
        public int Stars { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
