//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivity
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> VisitorId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public int ActivityId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Property Property { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
    }
}
